os: linux
language: python

jobs:
  include:
    - dist: focal
      arch: ppc64le
      script:
        - python hello_world.py
    - dist: focal
      arch: amd64
      script:
        - python hello_world.py
    - dist: bionic
      arch: amd64
      script:
        - python hello_world.py
    - dist: bionic
      arch: ppc64le
      script:
        - python hello_world.py
    - dist: xenial
      arch: amd64
      script:
        - python hello_world.py
    - dist: xenial
      arch: ppc64le
      script:
        - python hello_world.py
      
