os: linux
language: python

jobs:
  include:
    - dist: focal
      arch: ppc64le
      group: edge
      script:
        - sudo sh python_interpreter.sh
        - /opt/python380-at14/bin/python3.8 hello_world.py
        #- ./hello_world
        #- python3 hello_world.py
    - dist: bionic
      arch: ppc64le
      group: edge
      script:
        - sudo sh python_interpreter.sh
        - /opt/python380-at14/bin/python3.8 hello_world.py
        #- ./hello_world
        #- python3 hello_world.py
    - dist: xenial
      arch: ppc64le
      group: edge
      script:
        - sudo sh python_interpreter_xenial.sh
        - /opt/python380-at12/bin/python3.8 hello_world.py
      
