os: linux
language: python

jobs:
  include:
    - dist: focal
      arch: ppc64le
      group: edge
      script:
        #- python hello_world.py
        - /opt/at14.0/bin/gcc hello_world.py -o hello_world
        - python hello_world.py
    - dist: focal
      arch: amd64
      group: edge
      script:
        - python hello_world.py
    - dist: bionic
      arch: amd64
      group: edge
      script:
        - python hello_world.py
    - dist: bionic
      arch: ppc64le
      group: edge
      script:
        - python hello_world.py
    - dist: xenial
      arch: amd64
      group: edge
      script:
        - python hello_world.py
    - dist: xenial
      arch: ppc64le
      group: edge
      script:
        - python hello_world.py
      
