os: linux
language: python

jobs:
  include:
    - dist: focal
      arch: ppc64le
      group: edge
      script:
        - sudo sh python_interpreter.sh
        #- python3 hello_world.py
    - dist: bionic
      arch: ppc64le
      group: edge
      script:
        - sudo sh python_interpreter.sh
        #- python3 hello_world.py
    - dist: xenial
      arch: ppc64le
      group: edge
      script:
        - sudo sh python_interpreter_xenial.sh
        #- python3 hello_world.py
    - dist: xenial
      script:
        - sudo sh python_check_shell.sh
      
